name: API Artefacts Lab

on:
  workflow_dispatch:

jobs:
  criar-artefacto:
    runs-on: ubuntu-latest
    steps:
      - name: Criar ficheiro
        run: echo "OlÃ¡ Mafalda - Artefacto para API" > mensagem.txt

      - name: Upload artefacto
        uses: actions/upload-artifact@v4
        with:
          name: mensagem-api
          path: mensagem.txt
