name: Exercício 2 - Artefactos

on:
  workflow_dispatch:

jobs:
  criar-artefacto:
    runs-on: ubuntu-latest
    steps:
      - name: Criar ficheiro de texto
        run: echo "Olá Mafalda! Este é o artefacto do Job 1." > mensagem.txt

      - name: Fazer upload do artefacto
        uses: actions/upload-artifact@v4
        with:
          name: mensagem-job1
          path: mensagem.txt
  
  consumir-artefacto:
    runs-on: ubuntu-latest
    needs: criar-artefacto

    steps:
      - name: Download do artefacto
        uses: actions/download-artifact@v4
        with:
          name: mensagem-job1
          path: ./ficheiro-recebido

      - name: Mostrar conteúdo do ficheiro
        run: |
          echo "Conteúdo recebido:"
          cat ./ficheiro-recebido/mensagem.txt
