name: Teste de Triggers
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: #Permite correr manualmente no separador Actions

jobs:
  check-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Identificar Trigger
        run: echo "O workflow foi ativado pelo evento ${{github.event_name}}"
